services:
  api:
    build: .
    restart: unless-stopped
    env_file: [.env]
    volumes: [ "./data:/app/data" ]
    networks: [web]

  caddy:
    image: caddy:2.7
    restart: unless-stopped
    ports: ["80:80","443:443"]
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
    depends_on: [api]
    networks: [web]

networks: { web: {} }
volumes: { caddy_data: {}, caddy_config: {} }
